services:
  # --- O SERVIDOR DE FERRAMENTAS (MCP) ---
  servermcp:
    build: 
      context: .
      dockerfile: Dockerfile.mcp # Certifique-se de ter esse Dockerfile
    container_name: servermcp
    network_mode: "host" # Mantém a simplicidade para o túnel SSH
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./src:/app/src
      - ./remote-kubeconfig.yaml:/root/.kube/config
      - ./certs-remotos:/app/certs
    restart: always

  # --- O AGENTE (INTERFACE E LÓGICA) ---
  agentk:
    build: .
    container_name: agentk-mcp
    network_mode: "host"
    
    depends_on:
      - servermcp # Garante que o servidor suba antes do agente

    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app
      - KUBECONFIG=/root/.kube/config
      # Variável para o requisito v1.3: Seleção de Hardware
      - LLM_HARDWARE_TARGET=gpu 
    
    volumes:
      - ./src:/app/src
      - ./remote-kubeconfig.yaml:/root/.kube/config
      - ./certs-remotos:/app/certs
      # Adicionamos a pasta de logs para o requisito de métricas
      - ./logs:/app/logs 
      - ./tests:/app/tests 

    # --- REQUISITO v1.3: SELEÇÃO DE RECURSOS GPU ---
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

    restart: on-failure