# Dockerfile.mcp
FROM python:3.11-slim

WORKDIR /app

# Instala dependências básicas
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia o código fonte
COPY . .

# Comando para rodar o servidor (ajuste o caminho se o seu arquivo for diferente)
CMD ["python3", "src/main.py"]