apiVersion: v1
clusters:
- cluster:
    # Caminho INTERNO do container
    certificate-authority: /app/certs/ca.crt
    server: https://localhost:6443
  name: minikube-remoto
contexts:
- context:
    cluster: minikube-remoto
    user: minikube-user
  name: remote-context
current-context: remote-context
kind: Config
users:
- name: minikube-user
  user:
    # Caminhos INTERNOS do container
    client-certificate: /app/certs/client.crt
    client-key: /app/certs/client.key