apiVersion: v1
clusters:
- cluster:
    certificate-authority: /app/certs/ca.crt
    server: https://[IP_DO_SEU_MINIKUBE_AQUI]:8443
  name: minikube-local
contexts:
- context:
    cluster: minikube-local
    user: minikube-user
  name: local-context
current-context: local-context
kind: Config
users:
- name: minikube-user
  user:
    client-certificate: /app/certs/client.crt
    client-key: /app/certs/client.key